// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxU_xLfEDVohCVNylVmifThs5t5mBRX4',
    appId: '1:421670117881:web:8443b3594568b502781d28',
    messagingSenderId: '421670117881',
    projectId: 'authenticator-aman-321',
    authDomain: 'authenticator-aman-321.firebaseapp.com',
    storageBucket: 'authenticator-aman-321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMzb59B98WHMbCqI4bkW6JNTaslChyPOs',
    appId: '1:421670117881:android:5eb0189b68a018c2781d28',
    messagingSenderId: '421670117881',
    projectId: 'authenticator-aman-321',
    storageBucket: 'authenticator-aman-321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxn65ESSTuunNxVi16plPlfw5Hn9pPRb0',
    appId: '1:421670117881:ios:7784f3c1e2a3462c781d28',
    messagingSenderId: '421670117881',
    projectId: 'authenticator-aman-321',
    storageBucket: 'authenticator-aman-321.appspot.com',
    iosClientId: '421670117881-bk4jo11acspaqpauvto9snd6cc7ksj74.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxn65ESSTuunNxVi16plPlfw5Hn9pPRb0',
    appId: '1:421670117881:ios:7784f3c1e2a3462c781d28',
    messagingSenderId: '421670117881',
    projectId: 'authenticator-aman-321',
    storageBucket: 'authenticator-aman-321.appspot.com',
    iosClientId: '421670117881-bk4jo11acspaqpauvto9snd6cc7ksj74.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
