// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OlWlK4_chqi1FDKVD_iT1iFWD0d2Dxg',
    appId: '1:38460385050:web:aa114db70019cd9e03aea3',
    messagingSenderId: '38460385050',
    projectId: 'github-project-321',
    authDomain: 'github-project-321.firebaseapp.com',
    storageBucket: 'github-project-321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeKzjfzK6mN7MqfZgSbeX7wieQ-bQ33w',
    appId: '1:38460385050:android:a09c7ffa9598a72603aea3',
    messagingSenderId: '38460385050',
    projectId: 'github-project-321',
    storageBucket: 'github-project-321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYh3d_Fky4P95l5zk04itd-FQDgorIbRg',
    appId: '1:38460385050:ios:3cfacd1121211de003aea3',
    messagingSenderId: '38460385050',
    projectId: 'github-project-321',
    storageBucket: 'github-project-321.appspot.com',
    iosClientId: '38460385050-f6vmqm2fvvpe26oa5lvis3dt5mj67s70.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizQuestionsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYh3d_Fky4P95l5zk04itd-FQDgorIbRg',
    appId: '1:38460385050:ios:3cfacd1121211de003aea3',
    messagingSenderId: '38460385050',
    projectId: 'github-project-321',
    storageBucket: 'github-project-321.appspot.com',
    iosClientId: '38460385050-f6vmqm2fvvpe26oa5lvis3dt5mj67s70.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizQuestionsFirebase',
  );
}
