// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRogc1HHFf64ubHKcEBa78IVjVTS9uWG4',
    appId: '1:754398596000:web:453152467e4e86f20cf2c5',
    messagingSenderId: '754398596000',
    projectId: 'flutter-kellton',
    authDomain: 'flutter-kellton.firebaseapp.com',
    storageBucket: 'flutter-kellton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRaaVNkX6npVYOoETJG3cMQiEQWodtOfU',
    appId: '1:754398596000:android:d94d8d243b614b880cf2c5',
    messagingSenderId: '754398596000',
    projectId: 'flutter-kellton',
    storageBucket: 'flutter-kellton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDODEx4qDkz9hnl631GvNp5ZZhnY_UhYxY',
    appId: '1:754398596000:ios:3a9bf13db46a43f40cf2c5',
    messagingSenderId: '754398596000',
    projectId: 'flutter-kellton',
    storageBucket: 'flutter-kellton.appspot.com',
    iosClientId: '754398596000-fdb2tiub05v2eda3pvk2djno6npb2uqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedPreference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDODEx4qDkz9hnl631GvNp5ZZhnY_UhYxY',
    appId: '1:754398596000:ios:3a9bf13db46a43f40cf2c5',
    messagingSenderId: '754398596000',
    projectId: 'flutter-kellton',
    storageBucket: 'flutter-kellton.appspot.com',
    iosClientId: '754398596000-fdb2tiub05v2eda3pvk2djno6npb2uqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharedPreference',
  );
}
