// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvuG6-HDrYdhFoIO87ZYvNimhKje-exw',
    appId: '1:771218834286:web:87144ad92cb965edf8f77f',
    messagingSenderId: '771218834286',
    projectId: 'realtime-database-321',
    authDomain: 'realtime-database-321.firebaseapp.com',
    storageBucket: 'realtime-database-321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcbWfe2Ilb0yueac3c4Q5NLBfQ1yQg3s',
    appId: '1:771218834286:android:f8d4287ba363b2f2f8f77f',
    messagingSenderId: '771218834286',
    projectId: 'realtime-database-321',
    storageBucket: 'realtime-database-321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kC6dZ2Zni33wx9nSJddJ4Nh5eEIfz-s',
    appId: '1:771218834286:ios:4f7d7f1ab41ae4d9f8f77f',
    messagingSenderId: '771218834286',
    projectId: 'realtime-database-321',
    storageBucket: 'realtime-database-321.appspot.com',
    iosClientId: '771218834286-k5hcjr01ropkttnckr44kpniftdvoohn.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kC6dZ2Zni33wx9nSJddJ4Nh5eEIfz-s',
    appId: '1:771218834286:ios:4f7d7f1ab41ae4d9f8f77f',
    messagingSenderId: '771218834286',
    projectId: 'realtime-database-321',
    storageBucket: 'realtime-database-321.appspot.com',
    iosClientId: '771218834286-k5hcjr01ropkttnckr44kpniftdvoohn.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeDatabase',
  );
}
