// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EXHDAdEWxGnIExMoQW6DeK_0Xe6RtqE',
    appId: '1:883745726689:web:3361360c99b2614ee617a0',
    messagingSenderId: '883745726689',
    projectId: 'firebase-abhishek',
    authDomain: 'fir-abhishek.firebaseapp.com',
    storageBucket: 'firebase-abhishek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMhPKDaujJ-0b5OtCZTmFz28MEGz0Y6jk',
    appId: '1:883745726689:android:2798e662e074edcfe617a0',
    messagingSenderId: '883745726689',
    projectId: 'firebase-abhishek',
    storageBucket: 'firebase-abhishek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa9iMLJQmaH_2qKLL0yRlvpAPCYSTA8KQ',
    appId: '1:883745726689:ios:529353d3c53382d9e617a0',
    messagingSenderId: '883745726689',
    projectId: 'firebase-abhishek',
    storageBucket: 'firebase-abhishek.appspot.com',
    iosClientId: '883745726689-abcop0s6od77909gmbmo2klqddd378s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa9iMLJQmaH_2qKLL0yRlvpAPCYSTA8KQ',
    appId: '1:883745726689:ios:529353d3c53382d9e617a0',
    messagingSenderId: '883745726689',
    projectId: 'firebase-abhishek',
    storageBucket: 'firebase-abhishek.appspot.com',
    iosClientId: '883745726689-abcop0s6od77909gmbmo2klqddd378s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
