// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4tJs4A-XUPEQTNmbtge55dHdgTOIug7w',
    appId: '1:384296525636:web:eeff0b8d999b887fa28111',
    messagingSenderId: '384296525636',
    projectId: 'brave-quiz-321',
    authDomain: 'brave-quiz-321.firebaseapp.com',
    databaseURL: 'https://brave-quiz-321-default-rtdb.firebaseio.com',
    storageBucket: 'brave-quiz-321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDremNp5mB_OyVhBw0b5bYrzQNMoBMWGUw',
    appId: '1:384296525636:android:8f320cf9fa646bbba28111',
    messagingSenderId: '384296525636',
    projectId: 'brave-quiz-321',
    databaseURL: 'https://brave-quiz-321-default-rtdb.firebaseio.com',
    storageBucket: 'brave-quiz-321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bjgbmBdwOZhFboMc4xuNkwnUC6NBgqU',
    appId: '1:384296525636:ios:06df3fecc2a8babea28111',
    messagingSenderId: '384296525636',
    projectId: 'brave-quiz-321',
    databaseURL: 'https://brave-quiz-321-default-rtdb.firebaseio.com',
    storageBucket: 'brave-quiz-321.appspot.com',
    androidClientId: '384296525636-ss9k43v2mvrkrlq8paup38mb3b1t7fi2.apps.googleusercontent.com',
    iosClientId: '384296525636-ruhnvtalniqq4fd6boai65bjscres15h.apps.googleusercontent.com',
    iosBundleId: 'com.example.braveQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_bjgbmBdwOZhFboMc4xuNkwnUC6NBgqU',
    appId: '1:384296525636:ios:06df3fecc2a8babea28111',
    messagingSenderId: '384296525636',
    projectId: 'brave-quiz-321',
    databaseURL: 'https://brave-quiz-321-default-rtdb.firebaseio.com',
    storageBucket: 'brave-quiz-321.appspot.com',
    androidClientId: '384296525636-ss9k43v2mvrkrlq8paup38mb3b1t7fi2.apps.googleusercontent.com',
    iosClientId: '384296525636-ruhnvtalniqq4fd6boai65bjscres15h.apps.googleusercontent.com',
    iosBundleId: 'com.example.braveQuiz',
  );
}
